#!/bin/sh

# For the given GeoText directories, add a corpus field to the beginning of
# the data and remove all the non-informative fields (e.g. the arbitrarily-
# generated ID and bunches of useless Wikipedia fields).   Store into a
# subdirectory of $NEWCONVERTDIR.

NEWCONVERTDIR=frobconv
# Do it for one dir.
do_dir() {
  dir=$1
  textgrounder run opennlp.textgrounder.preprocess.FrobCorpus -a corpus=twitter-geotext-$dir -o $NEWCONVERTDIR/$dir -i $dir -r id -r redir -r namespace -r is_list_of -r is_disambig -r is_list -r incoming_links
  mv -f $NEWCONVERTDIR/$dir/* $dir
  rmdir $NEWCONVERTDIR/$dir
  rmdir $NEWCONVERTDIR
}

for x in ${1+"$@"}; do
  echo $x
  do_dir $x
done
