#!/bin/sh

# For the given directories, merge the metadata and old-style counts
# files into a new-style combined document file.  Store into a subdirectory
# of $NEWCONVERTDIR.

NEWCONVERTDIR=new-convert
# Do it for one dir.
do_dir() {
  dir=$1
  dirbase=`basename $dir`
  textgrounder run opennlp.textgrounder.preprocess.MergeMetadataAndOldCounts -o $NEWCONVERTDIR/$dirbase -i $dir --counts-file $dir/*-counts-only-coord-documents.txt*
  mv -f $NEWCONVERTDIR/$dir/* $dir
  rmdir $NEWCONVERTDIR/$dir
}

for x in ${1+"$@"}; do
  echo $x
  do_dir $x
done
