#!/bin/sh

# For the given directories, merge the metadata and old-style counts
# files into a new-style combined document file.  Store into a subdirectory
# of $NEWCONVERTDIR.

NEWCONVERTDIR=new-convert
# Do it for one dir.
do_dir() {
  dir=$1
  textgrounder run opennlp.textgrounder.preprocess.MergeMetadataAndOldCounts -o $NEWCONVERTDIR/$dir -i $dir --counts-file $dir/*-counts-only-coord-documents.txt.bz2
  mv -f $NEWCONVERTDIR/$dir/* $dir
  rmdir $NEWCONVERTDIR/$dir
  rmdir $NEWCONVERTDIR
}

for x in ${1+"$@"}; do
  echo $x
  do_dir $x
done
