#!/bin/sh

# Run wiki_disambig.py, passing it various useful arguments.  Extra arguments
# can be specified on the command line, which will override any existing
# arguments.
#
# See also 'run-run-disambig', which will run this script using 'nohup'
# while saving the output to a file.

if [ -z "$WIKIPEDIA_DATA_DIR" ]; then
  WIKIPEDIA_DATA_DIR='.'
fi

if [ -z "$WIKIPEDIA_AUX_DATA_DIR" ]; then
  WIKIPEDIA_AUX_DATA_DIR='.'
fi

PREFIX="$WIKIPEDIA_DATA_DIR/enwiki-20100905"
AUXPREFIX="$WIKIPEDIA_AUX_DATA_DIR"
TG_PYTHON_DIR="$HOME/devel/textgrounder/python"
TRCONLL_DEV_DIR="/groups/projects/pcl_travel/data/trconlldevtest/dev"
WIKI_DISAMBIG="$TG_PYTHON_DIR/wiki_disambig.py"

#DEBUG="--debug 2"
#DEBUG="--debug 0"
DEBUG="--debug 1"
#MAXTIME="--max-time-per-stage 5"
#MAXTIME="--max-time-per-stage 300"
#MAXTIME="--max-time-per-stage 10"

PICKLE_FILE="$PREFIX-coords-counts.pickled"
#UNPICKLE="--unpickle-file $PICKLE_FILE"
#PICKLE="--pickle-file $PICKLE_FILE"
PICKLE=
UNPICKLE=

STOPWORDS_FILE="--stopwords-file $AUXPREFIX/stopwords.english"
ARTICLE_DATA_FILE="--article-data-file $PREFIX-combined-article-data.txt"
COUNTS_FILE="--counts-file $PREFIX-counts-only-coord-articles.txt"
GAZETTEER_FILE="--gazetteer-file $AUXPREFIX/world-dataen-fixed.txt"

#MODE="pickle-only"
#MODE="match-only"
MODE="geotag-toponyms"
#MODE="geotag-documents"

MISCOPTS="--width-of-stat-region 1 --miles-per-region 100"
if [ "$MODE" = "geotag-toponyms" -o "$MODE" = "match-only" ]; then
  STRATEGY="--strategy baseline"
  # Don't need counts file with baseline-only strategy
  COUNTS_FILE=""
  #STRATEGY="--strategy naive-bayes-with-baseline"
  #STRATEGY="--strategy naive-bayes-no-baseline"
  #NBTYPE="--naive-bayes-weighting distance-weighted"
  EVALFILE="--eval-file $TRCONLL_DEV_DIR"
  EVALTYPE="--eval-format tr-conll"
  #EVALFILE="--eval-file $PREFIX-toponym-eval.txt"
elif [ "$MODE" = "geotag-documents" ]; then
  EVALTYPE="--eval-format wiki"
fi

$WIKI_DISAMBIG \
  $STOPWORDS_FILE \
  $ARTICLE_DATA_FILE \
  $COUNTS_FILE \
  $GAZETTEER_FILE \
  --mode "$MODE" \
  $MISCOPTS \
  $EVALFILE $EVALTYPE \
  $PICKLE $UNPICKLE $MAXTIME $STRATEGY $NBTYPE $DEBUG ${1+"$@"}
