#!/bin/sh

PICKLE_FILE="enwiki-20100905-coords-counts.pickled"
#UNPICKLE="--unpickle-file $PICKLE_FILE"
#PICKLE="--pickle-file $PICKLE_FILE"
PICKLE=
UNPICKLE=

DEBUG="--debug 1"
#MAXTIME="--max-time-per-stage 5"
#MAXTIME="--max-time-per-stage 10"

#MODE="--mode pickle-only"
#MODE="--mode match-only"
MODE="--mode geotag-toponyms"
#MODE="--mode geotag-articles"
STRATEGY="--strategy link-baseline"
#STRATEGY="--strategy naive-bayes-with-baseline"
#STRATEGY="--strategy naive-bayes-no-baseline"
#NBTYPE="--naive-bayes-weighting distance-weighted"
EVALFILE="--eval-file /groups/projects/pcl_travel/data/trconlldevtest/dev"
EVALTYPE="--eval-format tr-conll"
#EVALFILE="--eval-file enwiki-20100905-toponym-eval.txt"


$HOME/devel/textgrounder/python/wiki_disambig.py \
  --stopwords-file stopwords.english \
  --article-data-file enwiki-20100905-combined-article-data.txt \
  --words-coords-file enwiki-20100905-coords-counts.txt \
  --gazetteer-file world-dataen-fixed.txt \
  --width-of-nbregion 1 --region-size 100 \
  $EVALFILE $EVALTYPE \
  $PICKLE $UNPICKLE $MAXTIME $MODE $STRATEGY $NBTYPE $DEBUG ${1+"$@"}
