#!/bin/sh

# Run twitter_geotext_process.py, passing it various useful arguments.
# Extra arguments can be specified on the command line, which will override
# any existing arguments.

DEBUG="--debug 0"

if [ -z "$TEXTGROUNDER_PYTHON" ]; then
  if [ -z "$TEXTGROUNDER_DIR" ]; then
    echo "With TEXTGROUNDER_PYTHON unset, must set TEXTGROUNDER_DIR to point"
    echo "to top-level directory where TextGrounder is installed."
    exit 1
  fi
  TEXTGROUNDER_PYTHON="$TEXTGROUNDER_DIR/python"
fi

. $TEXTGROUNDER_PYTHON/config-wikigrounder

mkdir -p $GEOTEXT_OUTPUT_DIR

TWITTER_PROC="$TEXTGROUNDER_PYTHON/twitter_geotext_process.py"

$TWITTER_PROC --input-dir $GEOTEXT_INPUT_DIR --output-dir $GEOTEXT_OUTPUT_DIR $DEBUG ${1+"$@"}

