#!/bin/sh

#DEBUG="--debug 2"
DEBUG="--debug 0"
PREFIX="foobar"
#MAXTIME="--max-time-per-stage 5"
#MAXTIME="--max-time-per-stage 10"

#COORDS_FILE="--coords-file enwiki-20100905-just-titles-coords.txt"

#MODE="--generate-toponym-eval"
#PREFIX="enwiki-20100905-toponym-eval.txt"
#MISCOPTS="--redirect-file enwiki-20100905-filtered-redirects.txt"

#MODE="--find-redirects"
#PREFIX="enwiki-20100905-redirects.txt"

#MODE="--only-coords"
#PREFIX="enwiki-20100905-just-titles-coords.txt"

#MODE="--coords-counts"
#PREFIX="enwiki-20100905-coords-counts.txt"

#MODE="--find-links"
#PREFIX="enwiki-20100905-links-only-coord-articles.txt"

MODE="--generate-article-data"
PREFIX="enwiki-20100905-article-data.txt"
MISCOPTS="--disambig-id-file enwiki-20100905-pages-articles.disambig.id.txt"

SPLIT="--split-training-dev-test $PREFIX"

#OUTFILE="> $PREFIX"

bzcat enwiki-20100905-pages-articles.xml.bz2 | \
  $HOME/devel/textgrounder/python/processwiki.py \
  $COORDS_FILE $MAXTIME $SPLIT $MISCOPTS $DEBUG $MODE ${1+"$@"} $OUTFILE 
