#!/bin/sh

# Run disambig.py, passing it various useful arguments for running
# on Eisenstein et al (2010)'s Twitter data.  Extra arguments
# can be specified on the command line, which will override any existing
# arguments.
#
# See also 'run-run-twitter', which will run this script using 'nohup'
# while saving the output to a file.

if [ -z "$WIKIGROUNDER_DIR" ]; then
  if [ -z "$TEXTGROUNDER_DIR" ]; then
    echo "With WIKIGROUNDER_DIR unset, must set TEXTGROUNDER_DIR to point"
    echo "to top-level directory where TextGrounder is installed."
    exit 1
  fi
  WIKIGROUNDER_DIR="$TEXTGROUNDER_DIR/python"
fi

. $WIKIGROUNDER_DIR/config-wikigrounder

RUN_DISAMBIG="$WIKIGROUNDER_DIR/run-disambig"

####### Begin option processing

#opts=""

# Don't bother using getopt here.  Less portable (esp. on Mac OS X, where
# the default getopt doesn't support --long format), and hardly buys us
# much anything.

while true ; do
  case "$1" in
    --doc-thresh) GEOTEXT_OUTPUT_DIR="$GEOTEXT_TOP_DIR/output-$2-docthresh" ;
                  shift 2 ;;
    # A no-argument option ....
    #-n|--no-backup) opts="$opts --no-backup" ; shift ;;
    --) shift ; break ;;
    *) break ;;
  esac
done

####### End option processing


GEOTEXT_PREFIX="$GEOTEXT_OUTPUT_DIR/geotext-twitter"

COMBINED_ARTICLE_DATA_ARG="--article-data-file $GEOTEXT_PREFIX-combined-article-data.txt"
COUNTS_ARG="--counts-file $GEOTEXT_PREFIX-counts-only-coord-articles.txt"

$RUN_DISAMBIG $COMBINED_ARTICLE_DATA_ARG $COUNTS_ARG ${1+"$@"}
