#!/bin/sh

PREFIX="enwiki-20100905"
PROCESSWIKI="$HOME/devel/textgrounder/python/processwiki.py"

#DEBUG="--debug 2"
DEBUG="--debug 0"
#MAXTIME="--max-time-per-stage 5"
#MAXTIME="--max-time-per-stage 10"

COORDS_FILE="--coords-file $PREFIX-just-titles-coords.txt"

#MODE="--generate-toponym-eval"
#OUTFILE="$PREFIX-toponym-eval.txt"
#MISCOPTS="--redirect-file $PREFIX-filtered-redirects.txt"

#MODE="--find-redirects"
#OUTFILE="$PREFIX-redirects.txt"

#MODE="--only-coords"
#OUTFILE="$PREFIX-just-titles-coords.txt"

#MODE="--coords-counts"
#OUTFILE="$PREFIX-coords-counts.txt"

MODE="--find-links"
OUTFILE="$PREFIX-links-only-coord-articles.txt"

#MODE="--generate-article-data"
#OUTFILE="$PREFIX-article-data.txt"
#MISCOPTS="--disambig-id-file $PREFIX-pages-articles.disambig.id.txt"

SPLITPREFIX="$OUTFILE"
SPLITPREFIX="foobar"
#SPLIT="--split-training-dev-test $SPLITPREFIX"


INFILE="$PREFIX-pages-articles.xml.bz2"

OPTIONS="$COORDS_FILE $MAXTIME $SPLIT $MISCOPTS $DEBUG $MODE"
if [ -n "$OUTFILE" ]; then
  echo $INFILE '|' $PROCESSWIKI $OPTIONS ${1+"$@"} '>' $OUTFILE
  bzcat $INFILE | $PROCESSWIKI $OPTIONS ${1+"$@"} > $OUTFILE
else
  echo $INFILE '|' $PROCESSWIKI $OPTIONS ${1+"$@"}
  bzcat $INFILE | $PROCESSWIKI $OPTIONS ${1+"$@"}
fi
