#!/bin/sh

# Run disambig.py, passing it various useful arguments, including arguments
# for working with Wikipedia.  Extra arguments can be specified on the
# command line, which will override any existing arguments.
#
# See also 'run-run-wikipedia', which will run this script using 'nohup'
# while saving the output to a file.

if [ -z "$TEXTGROUNDER_PYTHON" ]; then
  if [ -z "$TEXTGROUNDER_DIR" ]; then
    echo "With TEXTGROUNDER_PYTHON unset, must set TEXTGROUNDER_DIR to point"
    echo "to top-level directory where TextGrounder is installed."
    exit 1
  fi
  TEXTGROUNDER_PYTHON="$TEXTGROUNDER_DIR/python"
fi

. $TEXTGROUNDER_PYTHON/config-wikigrounder

RUN_DISAMBIG="$TEXTGROUNDER_PYTHON/run-disambig"

$RUN_DISAMBIG $COMBINED_ARTICLE_DATA_ARG $COUNTS_ARG ${1+"$@"}
